### PR TITLE
Weapon setting for inventory display

### PR DESCRIPTION
**Pull request by SebbeJohansson**
- Adds a setting on WeaponSettings for whether or not the inventory display should show.
- Adds a cmd command to set that weapon setting.

### CODE REVIEW

**Comment by timmybo5** [comment]
I'm not a big fan of adding a UI setting to the base that is unrelated to the core weapon logic. What would be the use case of having a setting to disable the inventory of the demo hud globally?

**Comment by SebbeJohansson** [comment]
@timmybo5 in my small gamemode I made to test this code, I have no use for the inventory ui. But I still want to use your base!

**Comment by SebbeJohansson** [comment]
In my gamemode I only currently have one gun. And later on I will just have two (one melee weapon) with just a two weapon ui custom made.

https://github.com/SebbeJohansson/flying-sboxman

**Comment by timmybo5** [comment]
The base was made so you can separate all the pieces (base, hud, player, editor). You can just remove the hud folder like I did for the skeleton base https://github.com/timmybo5/swb-skeleton/tree/master/code

**Comment by SebbeJohansson** [comment]
@timmybo5 I would have assumed that you wanted to allow people to expand on it and provide prs back down to the base. But I guess its more of an example rather than a base?

**Comment by SebbeJohansson** [comment]
What about making a class that extends the weapon settings in base so that the example project has additional features related to the hud?

**Comment by timmybo5** [comment]
I don't see the use case of including a hide inventory setting to the base, so I will be closing this. If you have any other suggestions feel free to open a new pr.

**Pull request closed without merging**
